version: '3.8'

services:
  # Streamlit web application
  anomaly-detector:
    build:
      context: .
      target: production
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data:ro
      - ./output:/app/output
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development environment with hot reload
  anomaly-detector-dev:
    build:
      context: .
      target: development
    ports:
      - "8502:8501"
    volumes:
      - .:/app
      - /app/.venv
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_RUN_ON_SAVE=true
    profiles:
      - dev

  # CLI service for batch processing
  anomaly-detector-cli:
    build:
      context: .
      target: cli
    volumes:
      - ./data:/app/data:ro
      - ./output:/app/output
    profiles:
      - cli
    command: ["analysis.py", "--input", "/app/data/synthetic_dirty_transaction_logs.csv", "--output_dir", "/app/output"]

volumes:
  output_data:
    driver: local